-- Migration: Add shared rounds functionality
-- Run this in Supabase SQL Editor AFTER add_owner_permissions.sql

-- ============================================
-- 1. UPDATE ROUNDS TABLE FOR SHARING
-- ============================================

-- Add share_code column (6 alphanumeric characters, unique)
ALTER TABLE rounds ADD COLUMN IF NOT EXISTS share_code VARCHAR(6) UNIQUE;

-- Add collaborators column (array of user IDs who can edit this round)
ALTER TABLE rounds ADD COLUMN IF NOT EXISTS collaborators UUID[] DEFAULT '{}';

-- ============================================
-- 2. CREATE FUNCTION TO GENERATE SHARE CODE
-- ============================================

CREATE OR REPLACE FUNCTION generate_share_code()
RETURNS VARCHAR(6) AS $$
DECLARE
  chars TEXT := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  code VARCHAR(6) := '';
  i INTEGER;
BEGIN
  FOR i IN 1..6 LOOP
    code := code || substr(chars, floor(random() * length(chars) + 1)::integer, 1);
  END LOOP;
  RETURN code;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- 3. UPDATE RLS POLICIES FOR ROUNDS
-- ============================================

-- Drop existing user policies to recreate them
DROP POLICY IF EXISTS "Users can view own rounds" ON rounds;
DROP POLICY IF EXISTS "Users can insert own rounds" ON rounds;
DROP POLICY IF EXISTS "Users can update own rounds" ON rounds;
DROP POLICY IF EXISTS "Users can delete own rounds" ON rounds;

-- Users can view their own rounds OR rounds where they are collaborators
CREATE POLICY "Users can view own or shared rounds" ON rounds
  FOR SELECT USING (
    auth.uid() = user_id OR
    auth.uid() = ANY(collaborators)
  );

-- Users can insert their own rounds
CREATE POLICY "Users can insert own rounds" ON rounds
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Users can update their own rounds OR rounds where they are collaborators
CREATE POLICY "Users can update own or shared rounds" ON rounds
  FOR UPDATE USING (
    auth.uid() = user_id OR
    auth.uid() = ANY(collaborators)
  );

-- Only round owner can delete
CREATE POLICY "Users can delete own rounds" ON rounds
  FOR DELETE USING (auth.uid() = user_id);

-- ============================================
-- 4. CREATE INDEX FOR SHARE CODE AND COLLABORATORS
-- ============================================

CREATE INDEX IF NOT EXISTS idx_rounds_share_code ON rounds(share_code) WHERE share_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_rounds_collaborators ON rounds USING GIN(collaborators);

-- ============================================
-- 5. COMMENT THE NEW COLUMNS
-- ============================================

COMMENT ON COLUMN rounds.share_code IS 'Unique 6-character code for sharing this round with other users';
COMMENT ON COLUMN rounds.collaborators IS 'Array of user IDs who can view and edit this round';

-- ============================================
-- NOTE: The share_code is generated by the backend when sharing is enabled.
-- Collaborators are added when a user joins via share code.
-- ============================================
